name = "rad"
version = "0.1.0-dev"
description = "A task runner for Gleam projects"
licences = ["Apache-2.0"]
target = "javascript"

[repository]
repo = "rad"
user = "tynanbe"
type = "github"

[[links]]
href = "https://gleam.run/"
title = "Website"

[dependencies]
gleam_erlang = "~> 0.9"
gleam_http = "~> 3.0"
gleam_httpc = "~> 2.0"
gleam_json = "~> 0.5"
gleam_stdlib = "~> 0.22"
glint = "~> 0.8"
shellout = "~> 1.0"
snag = "~> 0.2"
thoas = "~> 0.2"
tomerl = "~> 0.5"

[dev-dependencies]
gleeunit = "~> 0.6"

[rad]
module = "rad/workbook/standard"
targets = ["erlang", "javascript"]
with = "javascript"

[[rad.formatters]]
name = "javascript"
check = ["rome", "ci", "--indent-style=space", "src", "test"]
run = ["rome", "format", "--indent-style=space", "--write", "src", "test"]

[[rad.tasks]]
path = ["purple", "heart"]
run = ["echo", "💜 The dream you'll have here is a dream within a dream."]
shortdoc = "💜 The dream you'll have here is a dream within a dream."

[[rad.tasks]]
path = ["sparkles"]
run = ["echo", "✨ It's been a long road getting here..."]

[[rad.tasks]]
path = ["sparkling", "heart"]
run = ["sh", "-c", "echo '💖 I was staring out the window and there it was, just fluttering there...' $(rad version)!"]
